includes("Window")
includes("Rendering")
includes("GameFramework")
includes("EngineSystem")

target("Modules")  
    set_kind("static")  
    add_files("*.cpp")  
    add_headerfiles("*.hpp")  
    add_deps("BasicPipeline", "Window","GameFramework","EngineSystem")  
    add_includedirs(".", "Window", "Rendering","GameFramework","EngineSystem")